apiVersion: v1
kind: Service
metadata:
  name: achpserver-service
spec:
  selector:
    app: achpserver
  ports:
  - port: 7000
    targetPort: 7000
    nodePort: 30002
    protocol: TCP
  type: NodePort
