apiVersion: v1
kind: Service
metadata:
  name: achpserver-service
spec:
  selector:
    app: myapp
    component: achpserver            # Selecting Pods with these labels
  ports:
    - port: 4000                  # Port on the Service
      targetPort: 4000            # Port on the Pod
  type: ClusterIP                 # Default type
