apiVersion: apps/v1
kind: Deployment
metadata:
  name: achpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: achpserver
  template:
    metadata:
      labels:
        app: achpserver
    spec:
      containers:
      - name: achpserver
        image: pgautam27/achpserver:v1.1
        ports:
        - containerPort: 7000
