apiVersion: v1
kind: Service
metadata:
  name: achpweb-service
spec:
  type: NodePort
  selector:
    app: myapp
    component: achpweb           # Selecting Pods with these labels
  ports:
    - port: 80                    # Port on the Service
      targetPort: 80              # Port on the Pod
      nodePort: 30001 # Port on the





# Create NodePort service for the frontend
# kubectl expose deployment achpweb-deployment --type=NodePort --name=achpweb-service --port=80 --target-port=80 --namespace=default

# Create ClusterIP service for the backend
# kubectl expose deployment achpserver-deployment --type=ClusterIP --name=achpserver-service --port=4000 --target-port=4000 --namespace=default
