apiVersion: apps/v1
kind: Deployment
metadata:
  name: achpweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: achpweb
  template:
    metadata:
      labels:
        app: achpweb
    spec:
      containers:
      - name: achpweb
        image: pgautam27/achpweb:v1.4
        ports:
        - containerPort: 6000
