apiVersion: apps/v1
kind: Deployment
metadata:
  name: anymserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anymserver
  template:
    metadata:
      labels:
        app: anymserver
    spec:
      containers:
      - name: anymserver
        image: gautamp27/anym-server:1.0
        ports:
        - containerPort: 7000
