apiVersion: apps/v1
kind: Deployment
metadata:
  name: anymweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anymweb
  template:
    metadata:
      labels:
        app: anymweb
    spec:
      containers:
      - name: anymweb
        image: gautamp27/anym-web:1.2
        ports:
        - containerPort: 6000
