apiVersion: v1
kind: Service
metadata:
  name: anymweb-service
spec:
  selector:
    app: anymweb
  ports:
  - port: 80           # External port (again browser-friendly)
    targetPort: 6000   # Your container's port
    protocol: TCP
  type: LoadBalancer
